### PR TITLE
HAProxy 2.2.19

### PR DESCRIPTION
**Pull request by hexa2k9**

### CODE REVIEW

**Review by jeffsheltren — APPROVED** [review]
Thanks!

**Comment by jeffsheltren** [comment]
haproxy22-2.2.19-1.el7.ius has been pushed to IUS Testing.

**Comment by hexa2k9** [comment]
Thanks. 

Updated one of our LBs receiving about 5% of traffic. Will report back soon.

**Comment by hexa2k9** [comment]
I consider this being STABLE.

We haven't seen issues over the last couple of days.

**Comment by jeffsheltren** [comment]
Thanks @hexa2k9 I'll plan to push this to stable early next week.

**Pull request merged**
