### PR TITLE
Latest Upstream 2.2.8

### PR DESCRIPTION
**Pull request by hexa2k9**

### CODE REVIEW

**Review by carlwgeorge — APPROVED** [review]

**Comment by carlwgeorge** [comment]
Thanks!

**Comment by carlwgeorge** [comment]
haproxy22-2.2.8-1.el7.ius has been published to the testing repo.

**Comment by hexa2k9** [comment]
Thank you!

I'll do my best to test things over the weekend on a couple of instances serving plain HTTPS/TCP traffic.

**Comment by hexa2k9** [comment]
Things were performing stable over the last couple of days, but may be it's worth to pick 2.2.9 (see #3) over this one.

**Pull request merged**
